[workspace]
resolver = "3"
members = ["cli", "libdrbug"]

[workspace.package]
name = "drbug"
version = "0.1.0"
edition = "2024"
authors = ["David R. Morrison"]
rust-version = "1.87"
license = "MIT"
readme = "README.md"

[workspace.dependencies]
clap = "4.5.40"
nix = "0.30.1"
rstest = "0.25.0"
