[package]
name = "libdrbug"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
anyhow = "1.0.98"
nix = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
